name: client-app-build-disabled

on:
  workflow_dispatch:

jobs:
  client-build-disabled:
    runs-on: ubuntu-latest

    steps:
      - name: Client build disabled
        run: |
          echo "La compilación del cliente está deshabilitada en CI."
          echo "Se compila únicamente la app de administración en admin-android-build.yml."
